# =====================================================================
# 파일 위치 : roles/myftp/vars/main.yml
# 역할      : FTP 사용자 비밀번호 변수 (강한 우선순위).
#             vault_ftp_password 변수 ansible-vault 로 암호화된 변수 사용 
# =====================================================================
---
ftp_password: "{{ vault_ftp_password }}"